[Main]
output_file_head = "surf_bulk_new111_ext"
input_2dmat = "./input.toml"
[Main.param]
z_margin = 0.001
slab_margin = 10.0
r_SiH = 1.48 #angstrom
theta = 109.5 #H-Si-H angle in degre
[Main.lattice]
unit_vec = [[4.000668747, 0.00000, 0.00000], [0.00000, 4.000668747, 0.00000]]
