[base]
dimension = 2

[solver]
name = "leed"
[solver.config]
path_to_solver = "./leedsatl/satl2.exe"
[solver.reference]
path_to_base_dir = "./base"

[algorithm]
name = "mapper"
label_list = ["z1", "z2"]
[algorithm.param]
mesh_path = "./MeshData.txt"
