[base]
dimension = 2
[solver]
name = "sxrd"
[solver.config]
sxrd_exec_file = "./sxrdcalc"
bulk_struc_in_file = "sic111-r3xr3.blk"
[solver.param]
scale_factor = 1.0
type_vector = [1, 2]
[[solver.param.domain]]
domain_occupancy = 1.0
  [[solver.param.domain.atom]]
    name = "Si"
    pos_center = [0.00000000, 0.00000000, 1.00000000]
    DWfactor = 0.0
    occupancy = 1.0
    displace_vector = [[1, 0.0, 0.0, 1.0]]
  [[solver.param.domain.atom]]
    name = "Si"
    pos_center = [0.33333333, 0.66666667, 1.00000000]
    DWfactor = 0.0
    occupancy = 1.0
    displace_vector = [[1, 0.0, 0.0, 1.0]]
  [[solver.param.domain.atom]]
    name = "Si"
    pos_center = [0.66666667, 0.33333333, 1.00000000]
    DWfactor = 0.0
    occupancy = 1.0
    displace_vector = [[1, 0.0, 0.0, 1.0]]
  [[solver.param.domain.atom]]
    name = "Si"
    pos_center = [0.33333333, 0.33333333, 1.20000000]
    DWfactor = 0.0
    occupancy = 1.0
    displace_vector = [[2, 0.0, 0.0, 1.0]]
[solver.reference]
f_in_file = "sic111-r3xr3_f.dat"
[algorithm]
name = "mapper"
label_list = ["z1", "z2"]
[algorithm.param]
mesh_path = "./MeshData.txt"
